# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # - 35.154.75.168:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   # - "rules/rules.yml"
  # - "second_rules.yml"
 
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]


  - job_name: "Docker Node"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["35.154.194.200:9323"]
        labels:
            region: "IN"
            team: "docker"
            env: "dev"
  - job_name: "my-dynamic-job"
    file_sd_configs:
      - files:
        - myservicediscoveryfile.yml
    relabel_configs:
    - source_labels: [region]
      regex:         'US'
      replacement:   'IN'
      target_label:  region
    - source_labels: [team]
      regex:         'web'
      replacement:   'Deploy'
      target_label:   team

  - job_name: " my-ec2-config"
    ec2_sd_configs:
       - region: "ap-south-1"
    relabel_configs:
    - source_labels: [__meta_ec2_public_ip]
      regex:         '(.*)'
      replacement:   '${1}:9100'
      target_label:  __address__

